# Generated by Django 3.1.4 on 2021-06-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210601_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcourses',
            old_name='coursname',
            new_name='coursename',
        ),
    ]
